### ISSUE TITLE
2.2411.2.html

### ISSUE THREAD

**Issue by cleitonme** [guigo613/alternative-wa-version#1]
A version of 2.2411.2.html is possible so as not to have to generate qrcode again... changing the version here only works if you delete the wwebjs_auth folder

**Comment by guigo613** [comment]
Added in version 2.2411.2, now only testing remains. If you could provide feedback on whether everything went smoothly, I'd appreciate it.

**Comment by cleitonme** [comment]
It worked, I don't need to read qrcode again and send videos
